### ISSUE TITLE
Overflow not working properly when paper-dialog has fixed width/ height

### ISSUE THREAD

**Issue by motss** [PolymerElements/paper-dialog-scrollable#38]
Explicit width and height renders `paper-dialog-scrollable` does not clip overflow content.
## Expected outcome

After giving explicit width and height, `paper-dialog-scrollable` clips overflow content and a scrollbar is added to show the rest of the content.
## Actual outcome

The content inside `paper-dialog-scrollable` overflows and it is visible outside of the element.
## Demo to reproduce

[Demo to reproduce](http://jsbin.com/kobeciwoto/1/edit?html,output)

**Comment by valdrinkoshi** [comment]
Hi @motss, this has been partially fixed on master. A workaround to fix this is setting the height `paper-dialog-scrollable` http://jsbin.com/kaseku/1/edit?html,output

**Comment by a8775** [comment]
When resizing the browser (firefox) I'm getting unusual effet:
![snip_20160301154723](https://cloud.githubusercontent.com/assets/14092227/13430377/131d9db4-dfc5-11e5-95d0-680893c18f90.png)

+1

**Comment by valdrinkoshi** [comment]
Hi @motss, since the `paper-dialog-scrollable`'s `scrollTarget` is the element that determines the total `max-width` and `max-height` of the `paper-dialog` (it is the `sizingTarget`), you should limit the `scrollTarget`'s width/height through the mixin `paper-dialog-scrollable`
http://jsbin.com/muravu/4/edit?html,output

``` css
  paper-dialog paper-dialog-scrollable {
    --paper-dialog-scrollable: {
      box-sizing: border-box;
      width: 360px;
      height: 640px;
    }
  }
```
